language: node_js
node_js:
  - "0.10.40"
addons:
  sauce_connect: true
before_script:
  - npm install
  - "
  if [ '$TRAVIS_PULL_REQUEST' = 'false' ];
  then
    npm start &
  fi"
script:
  - npm test
  - "
  if [ '$TRAVIS_PULL_REQUEST' = 'false' ];
  then
    npm run e2e-remote;
  fi"
  - "
  if [ '$TRAVIS_PULL_REQUEST' = 'false' ];
  then
    pkill node
  fi"

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
