language: node_js
node_js:
  - "0.10"
before_script:
  - npm install
notifications:
  email:
    recipients:
      - jsbin@leftlogic.com
  irc: "chat.freenode.net#jsbin"
    on_success: change
    on_failure: always
